title: 0xHardfork Blog
description: Cloud Security & Backend Development
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

social:
  github: https://github.com/0xHardfork
  email: mailto:nightfall2026@gmail.com
